---
# This automation simulates the use of the IKEA TRADFRI Dimmer control
# connected through ZHA.

# | Button      | Action                                                  |
# | ----------- | ------------------------------------------------------- |
# | on (short)  | Turn the light on if off, turns the light to max if on  |
# | off (short) | Turn the light off                                      |
# | on (long)   | Increase brightness                                     |
# | off (long)  | Decrease brightness                                     |

blueprint:
  source_url: https://github.com/ThePapaG/ha-blueprints/blob/main/z2m/IKEA/IKEA_TRADFRI_2_button.yaml

  name: Z2M - IKEA TRADFRI - 2 Button Remote - OnOff and Brightness Improved

  description: >-
    This automation simulates the use of the IKEA TRADFRI on/off switch
    connected through ZHA. Based on https://github.com/niro1987/homeassistant-config/blob/main/blueprints/automation/niro1987/zha_ikea_tradfri_2button_remote_brightness.yaml

  domain: automation

  input:
    remote:
      name: IKEA TRADFRI remote control
      description: Select the remote control you wish to use.
      selector:
        entity:
          integration: mqtt
          domain: sensor
    light:
      name: Light
      description: Select the light entity you wish to control.
      selector:
        entity:
          filter:
            - domain: light
    speed:
      name: Speed
      description: The speed in which to update the light when the button is held.
      selector:
        number:
          min: 100
          max: 1000
          step: 100
          unit_of_measurement: milliseconds
          mode: slider
      default: 500
    
    change:
      name: Change
      description: The step size in percentage.
      selector:
        number:
          min: 1
          max: 100
          step: 1
          mode: slider
      default: 10

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input "remote"
    attribute: action

variables:
  var_speed: !input speed
  var_change: !input change
  var_light: !input light
  command: '{{ trigger.to_state.state }}'

condition:
  - condition: template
    value_template: "{{ command != ''}}"

action:
  - choose:
      # Short press up
      - conditions:
          - condition: template
            value_template: "{{ command == 'on' }}"
        sequence:
          - choose:
              # If the light is off turn on to the last level
              - conditions:
                  - condition: state
                    entity_id: !input light
                    state: "off"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: !input light
                    data:
                      transition: "{{ (var_speed / 1000)|float }}"
              # If the light is on then turn on to max
              - conditions:
                  - condition: state
                    entity_id: !input light
                    state: "on"
                sequence:
                  - service: light.turn_on
                    data:
                      brightness: 254
                      transition: "{{ (var_speed / 1000)|float }}"
                    target:
                      entity_id: !input light
      # Long press up
      - conditions:
          - condition: template
            value_template: "{{ command == 'brightness_move_up' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ (repeat.index < 500) }}"
              sequence:
                - choose:
                    # Light is off so turn it on to 1
                    - conditions:
                        - condition: template
                          value_template: "{{ is_state(var_light, 'off') }}"
                      sequence:
                        - service: light.turn_on
                          target:
                            entity_id: !input light
                          data:
                            brightness: 1
                            transition: "{{ (var_speed / 1000)|float }}"
                  # Anything else just dim up
                  default:
                    - service: light.turn_on
                      target:
                        entity_id: !input light
                      data:
                        brightness_step_pct: "{{ var_change }}"
                        transition: "{{ (var_speed / 1000)|float }}"
                - delay:
                    milliseconds: "{{ var_speed }}"
      # Short press down
      - conditions:
          - condition: template
            value_template: "{{ command == 'off' }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input light
            data:
              transition: "{{ (var_speed / 1000)|float }}"

      # Long press down
      - conditions:
          - condition: template
            value_template: "{{ command == 'brightness_move_down' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ (repeat.index < 500) }}"
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: !input light
                  data:
                    brightness_step_pct: "{{ (var_change * -1)|int }}"
                    transition: "{{ (var_speed / 1000)|float }}"
                - delay:
                    milliseconds: "{{ var_speed }}"

    # Any other event will cancel the repeat loops (i.e. releasing the [on|off] button)
    default: []